
project_id = "biomfysnhqbarbymhivc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.n8n-webhook]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.meetings-webhook]
verify_jwt = false
