// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biomfysnhqbarbymhivc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpb21meXNuaHFiYXJieW1oaXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDg0MDYsImV4cCI6MjA3MjE4NDQwNn0.n7SZZ8Rjy1bPSXlB4eo1j4-uhLeQ7dUn9TvJgTYU2mU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});